package com.example.playerapp.ui.model

enum class MusicCategoryType(val value : String) {
    UNKNOWN(""),
    PODCAST("PODCAST"),
    EVENT("EVENT"),
    MADE_FOR_U("MADE_FOR_U"),
    NEW_RELEASES("NEW_RELEASES"),
    HINDI("HINDI"),
    PUNJABI("PUNJABI"),
    TAMIL("TAMIL"),
    TELUGU("TELUGU"),
    CHARTS("CHARTS"),
    POP("POP"),
    INDIE("INDIE"),
    TRENDING("TRENDING"),
    LOVE("LOVE"),
    DISCOVER("DISCOVER"),
    RADIO("RADIO"),
    MOOD("MOOD"),
    PARTY("PARTY"),
    DECADES("DECADES"),
    DEVOTIONAL("DEVOTIONAL"),
    HIP_HOP("HIP_HOP"),
    DANCE_ELECTRIC("DANCE_ELECTRIC"),
    STUDENT("STUDENT"),
    CHILL("CHILL"),
    GAMING("GAMING"),
}